    $ for arg in {a..z}; do date_arg $arg; done
    a: <Sat>
    b: <May>
    c: <Sat May 18 10:34:10 2019>
    d: <18>
    e: <18>
    f: <f>
    g: <19>
    h: <May>
    i: <i>
    j: <138>
    k: <10>
    l: <10>
    m: <05>
    n: <
    >
    o: <o>
    p: <AM>
    q: <q>
    r: <10:34:10 AM>
    s: <1558190050>
    t: <	>
    u: <6>
    v: <18-May-2019>
    w: <6>
    x: <05/18/2019>
    y: <19>
    z: <-0400>
    $ ...
